/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-08 04:18:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Marks in bar chart</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("<div id=\"container\"\t style=\"min-width:310px; height:400px; margin:0 auto\"></div>\r\n");
      out.write("<script>\r\n");
      out.write("Highcharts.chart('container', {\r\n");
      out.write("    chart: {\r\n");
      out.write("        type: 'column'\r\n");
      out.write("    },\r\n");
      out.write("    title: {\r\n");
      out.write("        text: 'Monthly Average Rainfall'\r\n");
      out.write("    },\r\n");
      out.write("    subtitle: {\r\n");
      out.write("        text: 'Source: WorldClimate.com'\r\n");
      out.write("    },\r\n");
      out.write("    xAxis: {\r\n");
      out.write("        categories: [\r\n");
      out.write("            'Tamil',\r\n");
      out.write("            'English',\r\n");
      out.write("            'Mathematics',\r\n");
      out.write("            'Physics',\r\n");
      out.write("            'Chemistry',\r\n");
      out.write("            'Biology'\r\n");
      out.write("        ],\r\n");
      out.write("        crosshair: true\r\n");
      out.write("    },\r\n");
      out.write("    yAxis: {\r\n");
      out.write("        min: 0,\r\n");
      out.write("        title: {\r\n");
      out.write("            text: 'Rainfall (mm)'\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    tooltip: {\r\n");
      out.write("        headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',\r\n");
      out.write("        pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td>' +\r\n");
      out.write("            '<td style=\"padding:0\"><b>{point.y:.1f} mm</b></td></tr>',\r\n");
      out.write("        footerFormat: '</table>',\r\n");
      out.write("        shared: true,\r\n");
      out.write("        useHTML: true\r\n");
      out.write("    },\r\n");
      out.write("    plotOptions: {\r\n");
      out.write("        column: {\r\n");
      out.write("            pointPadding: 0.2,\r\n");
      out.write("            borderWidth: 0\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("    series: [\r\n");
      out.write("    {\r\n");
      out.write("        name: 'muthu',\r\n");
      out.write("        data: [156, 128, 146, 180, 167, 120]\r\n");
      out.write("\r\n");
      out.write("    }/*, {\r\n");
      out.write("        name: 'Guru',\r\n");
      out.write("        data: [157, 186, 182, 164, 197, 149]\r\n");
      out.write("\r\n");
      out.write("    }, {\r\n");
      out.write("        name: 'Prasanna',\r\n");
      out.write("        data: [168, 197, 189, 168, 159, 178]\r\n");
      out.write("\r\n");
      out.write("    }, {\r\n");
      out.write("        name: 'aathi',\r\n");
      out.write("        data: [178, 186, 169, 184, 139, 152]\r\n");
      out.write("\r\n");
      out.write("    }*/]\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
