/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-19 09:30:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Product</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h4>\r\n");
      out.write("\t\t\tProduct from Categories\r\n");
      out.write("\t\t</h4>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<label for=\"categories\">Categories</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"categories\" onchange=\"loadPro()\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"product\">Products</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"product\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\tloadDetails();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var categories = [];\r\n");
      out.write("var product = [];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadDetails(){\r\n");
      out.write("$.ajax({url: \"http://localhost:8080/RESTfulExample/rest/admin/overload\", \r\n");
      out.write("\tsuccess: function(result){\r\n");
      out.write("\t\tconsole.log(result);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcategories = result.categories;\r\n");
      out.write("\t\tproduct = result.product;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"categories\", categories, \"product\", product);\r\n");
      out.write("\t\t\tfor(i=0; i < categories.length; i++) {\r\n");
      out.write("\t\t\t$('#categories').append(new Option(categories[i].categoryName, categories[i].categoryId+\"\"));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tloadPro();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("function loadPro(){\r\n");
      out.write("\tvar selectedCategoryId = $('#categories').val();\r\n");
      out.write("\t$('#product').empty();\r\n");
      out.write("\tconsole.log(\"selectedCategoryId\", selectedCategoryId, \"product\", product);\r\n");
      out.write("\t\tfor(i=0; i < product.length; i++) {\r\n");
      out.write("\t\t\tif(product[i].categoryId+\"\" == selectedCategoryId){\r\n");
      out.write("\t\t\t\tconsole.log(\"categoryID matched\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(product[i].categoryId == selectedCategoryId){\r\n");
      out.write("\t\t\t\t$('#product').append(new Option(product[i].productName, product[i].productId+\"\"));\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
