/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-18 09:05:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class line_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Day Vs Temperature</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<button>Get Chart</button>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\"\r\n");
      out.write("\t\tstyle=\"min-width: 310px; height: 400px; margin: 0 auto\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("    $(\"button\").click(function(){\r\n");
      out.write("    \t$.ajax({url: \"http://localhost:8080/RESTfulExample/rest/tabletemp/Temp\", \r\n");
      out.write("        \tsuccess: function(result){\r\n");
      out.write("        \t\tconsole.log(result);\r\n");
      out.write("        \t\tvar seriesData = [];\r\n");
      out.write("        \t\tvar tmpData = [];\r\n");
      out.write("        \t\tfor(i=0;i<result.length;i++){\r\n");
      out.write("        \t\t\tconsole.log(result[i].day);\r\n");
      out.write("        \t\t\ttmpData = [\r\n");
      out.write("        \t\t\t\t\t\tDate.UTC(new Date(result[i].day).getFullYear(),\r\n");
      out.write("        \t\t\t\t\t\t\t\tnew Date(result[i].day).getMonth(),\r\n");
      out.write("        \t\t\t\t\t\t\t\tnew Date(result[i].day).getDate()\r\n");
      out.write("        \t\t\t\t\t\t\t\t),\r\n");
      out.write("        \t\t\t\t\t\tresult[i].temperature\r\n");
      out.write("        \t\t\t\t\t]\r\n");
      out.write("        \t\t\tseriesData.push(tmpData);\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t\tconsole.log(seriesData);\r\n");
      out.write("        \t\r\n");
      out.write("\t\t\tHighcharts.chart('container', {\r\n");
      out.write("   \t\t\t\t\t\t chart: {\r\n");
      out.write("   \t\t\t\t\t\t\tzoomType: 'x'\r\n");
      out.write("   \t\t\t\t\t\t },\r\n");
      out.write("   \t\t\t\t\t\t title: {\r\n");
      out.write("     \t\t\t\t\t\t    text: 'Day vs Temperature'\r\n");
      out.write("    \t\t\t\t\t },\r\n");
      out.write("   \t\t\t\t\t\t xAxis: {\r\n");
      out.write("   \t\t\t\t\t\t\ttype: 'datetime',\r\n");
      out.write("   \t\t\t\t\t\t\t dateTimeLabelFormats: {\r\n");
      out.write("   \t\t\t\t\t\t\t\tmillisecond: '%H:%M:%S.%L',\r\n");
      out.write("   \t\t\t\t\t\t\t\tsecond: '%H:%M:%S',\r\n");
      out.write("   \t\t\t\t\t\t\t\tminute: '%H:%M',\r\n");
      out.write("   \t\t\t\t\t\t\t\thour: '%H:%M',\r\n");
      out.write("   \t\t\t\t\t\t\t\tday: '%e. %b %Y'\r\n");
      out.write("   \t\t\t\t\t         }\r\n");
      out.write("    \t\t\t\t\t },\t\t\t\r\n");
      out.write("   \t\t\t\t\t\t yAxis: {\r\n");
      out.write("       \t\t\t\t\t\t\t title: {\r\n");
      out.write("            \t\t\t\t\t\t\ttext: 'Temperature (°C)'\r\n");
      out.write("        \t\t\t\t\t\t }\r\n");
      out.write("    \t\t\t\t\t },\r\n");
      out.write("    \t\t\t\t\t\t\t\t tooltip: {\r\n");
      out.write("    \t\t\t\t        \t\t        headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',\r\n");
      out.write("    \t\t\t\t        \t\t        pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td>' +\r\n");
      out.write("    \t\t\t\t        \t\t            '<td style=\"padding:0\"><b>{point.y:.1f}</b></td></tr>',\r\n");
      out.write("    \t\t\t\t        \t\t        footerFormat: '</table>',\r\n");
      out.write("    \t\t\t\t        \t\t        shared: true,\r\n");
      out.write("    \t\t\t\t        \t\t        useHTML: true\r\n");
      out.write("    \t\t\t\t        \t\t  },\r\n");
      out.write("    \t\t\t\t        \t\t    plotOptions: {\r\n");
      out.write("    \t\t\t\t        \t\t    \t area: {\r\n");
      out.write("    \t\t\t\t        \t\t                fillColor: {\r\n");
      out.write("    \t\t\t\t        \t\t                    linearGradient: {\r\n");
      out.write("    \t\t\t\t        \t\t                        x1: 0,\r\n");
      out.write("    \t\t\t\t        \t\t                        y1: 0,\r\n");
      out.write("    \t\t\t\t        \t\t                        x2: 0,\r\n");
      out.write("    \t\t\t\t        \t\t                        y2: 1\r\n");
      out.write("    \t\t\t\t        \t\t                     },\r\n");
      out.write("    \t\t\t\t        \t\t                    stops: [\r\n");
      out.write("    \t\t\t\t        \t\t                        [0, Highcharts.getOptions().colors[0]],\r\n");
      out.write("    \t\t\t\t        \t\t                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]\r\n");
      out.write("    \t\t\t\t        \t\t                    ]\r\n");
      out.write("    \t\t\t\t        \t\t                  },\r\n");
      out.write("    \t\t\t\t        \t\t                marker: {\r\n");
      out.write("    \t\t\t\t        \t\t                    radius: 2\r\n");
      out.write("    \t\t\t\t        \t\t                },\r\n");
      out.write("    \t\t\t\t        \t\t                lineWidth: 1,\r\n");
      out.write("    \t\t\t\t        \t\t                states: {\r\n");
      out.write("    \t\t\t\t        \t\t                    hover: {\r\n");
      out.write("    \t\t\t\t        \t\t                        lineWidth: 1\r\n");
      out.write("    \t\t\t\t        \t\t                    }\r\n");
      out.write("    \t\t\t\t        \t\t                },\r\n");
      out.write("    \t\t\t\t        \t\t                threshold: null\r\n");
      out.write("    \t\t\t\t        \t\t            },\r\n");
      out.write("    \t\t\t\t        \t\t    },\r\n");
      out.write("    \t\t\t\t\tseries:[{\r\n");
      out.write("    \t\t\t            type: 'area',\r\n");
      out.write("    \t\t\t            name: 'Date',\r\n");
      out.write("    \t\t\t            data: seriesData\r\n");
      out.write("    \t\t\t        }] \r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t });\r\n");
      out.write("        \t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\terror : function (a,b,c){\r\n");
      out.write("\t\t\t\tconsole.log(a,b,c);\r\n");
      out.write("\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
