/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-05 07:16:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class query_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    $(\"button\").click(function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("        $.ajax({url: \"http://localhost:8080/RESTfulExample/rest/data/marks/\"+$(\"#name\").val(), \r\n");
      out.write("        \tsuccess: function(result){\r\n");
      out.write("        \t\tconsole.log(result);\r\n");
      out.write("            \t$(\"#div1\").html(\"Name : \"+result.name);\r\n");
      out.write("            \t$(\"#div2\").html(\"DateOfBirth : \"+result.dateofbirth);\r\n");
      out.write("            \t$(\"#div3\").html(\"Tamil : \"+result.tamil);\r\n");
      out.write("            \t$(\"#div4\").html(\"English : \"+result.english);\r\n");
      out.write("            \t$(\"#div5\").html(\"Mathematics : \"+result.mathematics);\r\n");
      out.write("            \t$(\"#div6\").html(\"Physics : \"+result.physics);\r\n");
      out.write("            \t$(\"#div7\").html(\"Chemistry : \"+result.chemistry);\r\n");
      out.write("            \t$(\"#div8\").html(\"Boilogy : \"+result.biology);\r\n");
      out.write("            \tvar x,y,z,cut_off=0,total=0;\r\n");
      out.write("            \ttotal=result.tamil+result.english+result.mathematics+result.physics+result.chemistry+result.biology;\r\n");
      out.write("            \tx=result.physics/4;\r\n");
      out.write("            \ty=result.chemistry/4;\r\n");
      out.write("            \tz=result.biology/2;\r\n");
      out.write("            \tcut_off=x+y+z;\r\n");
      out.write("            \t$(\"#div9\").html(\"Total : \"+total);\r\n");
      out.write("            \t$(\"#div0\").html(\"CutOff : \"+cut_off);\r\n");
      out.write("        \t},\r\n");
      out.write("        \terror : function (a,b,c){\r\n");
      out.write("        \t\tconsole.log(a,b,c);\r\n");
      out.write("        \t}\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Mark sheet</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("Enter the name:\r\n");
      out.write("<br>\r\n");
      out.write("\t<input type=\"text\" id=\"name\" value=\"\">\r\n");
      out.write("\t<br>\r\n");
      out.write("<div id=\"div1\"></div>\r\n");
      out.write("<div id=\"div2\"></div>\r\n");
      out.write("<div id=\"div3\"></div>\r\n");
      out.write("<div id=\"div4\"></div>\r\n");
      out.write("<div id=\"div5\"></div>\r\n");
      out.write("<div id=\"div6\"></div>\r\n");
      out.write("<div id=\"div7\"></div>\r\n");
      out.write("<div id=\"div8\"></div>\r\n");
      out.write("<div id=\"div9\"></div>\r\n");
      out.write("<div id=\"div0\"></div>\r\n");
      out.write("\r\n");
      out.write("<button>Get Details</button>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
