/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-08 04:37:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class table_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head><script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Marks table</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<button>Get Details</button>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\"\t style=\"min-width:310px; height:400px; margin:0 auto\"></div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    $(\"button\").click(function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("        $.ajax({url: \"http://localhost:8080/RESTfulExample/rest/table/marks\", \r\n");
      out.write("        \tsuccess: function(result){\r\n");
      out.write("        \t\tconsole.log(result);\r\n");
      out.write("        \t\tvar seriesData = [];\r\n");
      out.write("        \t\tvar tmpData = {};\r\n");
      out.write("        \t\tfor(i=0;i<result.length;i++){\r\n");
      out.write("        \t\t\tconsole.log(result[i].name);\r\n");
      out.write("        \t\t\ttmpData = {\r\n");
      out.write("        \t\t\t\t\t\tname : result[i].name,\r\n");
      out.write("        \t\t\t\t\t\tdata :[result[i].tamil,result[i].english,result[i].mathematics,result[i].physics,result[i].chemistry,result[i].biology ]\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\tseriesData.push(tmpData);\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tconsole.log(seriesData);\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tHighcharts.chart('container', {\r\n");
      out.write("        \t\t    chart: {\r\n");
      out.write("        \t\t        type: 'column'\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    title: {\r\n");
      out.write("        \t\t        text: 'Monthly Average Rainfall'\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    subtitle: {\r\n");
      out.write("        \t\t        text: 'Source: WorldClimate.com'\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    xAxis: {\r\n");
      out.write("        \t\t        categories: [\r\n");
      out.write("        \t\t            'Tamil',\r\n");
      out.write("        \t\t            'English',\r\n");
      out.write("        \t\t            'Mathematics',\r\n");
      out.write("        \t\t            'Physics',\r\n");
      out.write("        \t\t            'Chemistry',\r\n");
      out.write("        \t\t            'Biology'\r\n");
      out.write("        \t\t        ],\r\n");
      out.write("        \t\t        crosshair: true\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    yAxis: {\r\n");
      out.write("        \t\t        min: 0,\r\n");
      out.write("        \t\t        title: {\r\n");
      out.write("        \t\t            text: 'Marks'\r\n");
      out.write("        \t\t        }\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    tooltip: {\r\n");
      out.write("        \t\t        headerFormat: '<span style=\"font-size:10px\">{point.key}</span><table>',\r\n");
      out.write("        \t\t        pointFormat: '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td>' +\r\n");
      out.write("        \t\t            '<td style=\"padding:0\"><b>{point.y:.1f}</b></td></tr>',\r\n");
      out.write("        \t\t        footerFormat: '</table>',\r\n");
      out.write("        \t\t        shared: true,\r\n");
      out.write("        \t\t        useHTML: true\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    plotOptions: {\r\n");
      out.write("        \t\t        column: {\r\n");
      out.write("        \t\t            pointPadding: 0.2,\r\n");
      out.write("        \t\t            borderWidth: 0\r\n");
      out.write("        \t\t        }\r\n");
      out.write("        \t\t    },\r\n");
      out.write("        \t\t    series: seriesData\r\n");
      out.write("        \t\t});\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t},\r\n");
      out.write("        \terror : function (a,b,c){\r\n");
      out.write("        \t\tconsole.log(a,b,c);\r\n");
      out.write("        \t}\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
