/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2017-07-06 05:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tablecre_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar dataSet = [\r\n");
      out.write("\t\t\t\t[ \"Tiger Nixon\", \"System Architect\", \"Edinburgh\", \"5421\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/04/25\", \"$320,800\" ],\r\n");
      out.write("\t\t\t\t[ \"Garrett Winters\", \"Accountant\", \"Tokyo\", \"8422\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/07/25\", \"$170,750\" ],\r\n");
      out.write("\t\t\t\t[ \"Ashton Cox\", \"Junior Technical Author\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"1562\", \"2009/01/12\", \"$86,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Cedric Kelly\", \"Senior Javascript Developer\", \"Edinburgh\",\r\n");
      out.write("\t\t\t\t\t\t\"6224\", \"2012/03/29\", \"$433,060\" ],\r\n");
      out.write("\t\t\t\t[ \"Airi Satou\", \"Accountant\", \"Tokyo\", \"5407\", \"2008/11/28\",\r\n");
      out.write("\t\t\t\t\t\t\"$162,700\" ],\r\n");
      out.write("\t\t\t\t[ \"Brielle Williamson\", \"Integration Specialist\", \"New York\",\r\n");
      out.write("\t\t\t\t\t\t\"4804\", \"2012/12/02\", \"$372,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Herrod Chandler\", \"Sales Assistant\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"9608\", \"2012/08/06\", \"$137,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Rhona Davidson\", \"Integration Specialist\", \"Tokyo\", \"6200\",\r\n");
      out.write("\t\t\t\t\t\t\"2010/10/14\", \"$327,900\" ],\r\n");
      out.write("\t\t\t\t[ \"Colleen Hurst\", \"Javascript Developer\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"2360\", \"2009/09/15\", \"$205,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Sonya Frost\", \"Software Engineer\", \"Edinburgh\", \"1667\",\r\n");
      out.write("\t\t\t\t\t\t\"2008/12/13\", \"$103,600\" ],\r\n");
      out.write("\t\t\t\t[ \"Jena Gaines\", \"Office Manager\", \"London\", \"3814\",\r\n");
      out.write("\t\t\t\t\t\t\"2008/12/19\", \"$90,560\" ],\r\n");
      out.write("\t\t\t\t[ \"Quinn Flynn\", \"Support Lead\", \"Edinburgh\", \"9497\",\r\n");
      out.write("\t\t\t\t\t\t\"2013/03/03\", \"$342,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Charde Marshall\", \"Regional Director\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"6741\", \"2008/10/16\", \"$470,600\" ],\r\n");
      out.write("\t\t\t\t[ \"Haley Kennedy\", \"Senior Marketing Designer\", \"London\",\r\n");
      out.write("\t\t\t\t\t\t\"3597\", \"2012/12/18\", \"$313,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Tatyana Fitzpatrick\", \"Regional Director\", \"London\", \"1965\",\r\n");
      out.write("\t\t\t\t\t\t\"2010/03/17\", \"$385,750\" ],\r\n");
      out.write("\t\t\t\t[ \"Michael Silva\", \"Marketing Designer\", \"London\", \"1581\",\r\n");
      out.write("\t\t\t\t\t\t\"2012/11/27\", \"$198,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Paul Byrd\", \"Chief Financial Officer (CFO)\", \"New York\",\r\n");
      out.write("\t\t\t\t\t\t\"3059\", \"2010/06/09\", \"$725,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Gloria Little\", \"Systems Administrator\", \"New York\", \"1721\",\r\n");
      out.write("\t\t\t\t\t\t\"2009/04/10\", \"$237,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Bradley Greer\", \"Software Engineer\", \"London\", \"2558\",\r\n");
      out.write("\t\t\t\t\t\t\"2012/10/13\", \"$132,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Dai Rios\", \"Personnel Lead\", \"Edinburgh\", \"2290\",\r\n");
      out.write("\t\t\t\t\t\t\"2012/09/26\", \"$217,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Jenette Caldwell\", \"Development Lead\", \"New York\", \"1937\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/09/03\", \"$345,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Yuri Berry\", \"Chief Marketing Officer (CMO)\", \"New York\",\r\n");
      out.write("\t\t\t\t\t\t\"6154\", \"2009/06/25\", \"$675,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Caesar Vance\", \"Pre-Sales Support\", \"New York\", \"8330\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/12/12\", \"$106,450\" ],\r\n");
      out.write("\t\t\t\t[ \"Doris Wilder\", \"Sales Assistant\", \"Sidney\", \"3023\",\r\n");
      out.write("\t\t\t\t\t\t\"2010/09/20\", \"$85,600\" ],\r\n");
      out.write("\t\t\t\t[ \"Angelica Ramos\", \"Chief Executive Officer (CEO)\", \"London\",\r\n");
      out.write("\t\t\t\t\t\t\"5797\", \"2009/10/09\", \"$1,200,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Gavin Joyce\", \"Developer\", \"Edinburgh\", \"8822\",\r\n");
      out.write("\t\t\t\t\t\t\"2010/12/22\", \"$92,575\" ],\r\n");
      out.write("\t\t\t\t[ \"Jennifer Chang\", \"Regional Director\", \"Singapore\", \"9239\",\r\n");
      out.write("\t\t\t\t\t\t\"2010/11/14\", \"$357,650\" ],\r\n");
      out.write("\t\t\t\t[ \"Brenden Wagner\", \"Software Engineer\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"1314\", \"2011/06/07\", \"$206,850\" ],\r\n");
      out.write("\t\t\t\t[ \"Fiona Green\", \"Chief Operating Officer (COO)\",\r\n");
      out.write("\t\t\t\t\t\t\"San Francisco\", \"2947\", \"2010/03/11\", \"$850,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Shou Itou\", \"Regional Marketing\", \"Tokyo\", \"8899\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/08/14\", \"$163,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Michelle House\", \"Integration Specialist\", \"Sidney\", \"2769\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/06/02\", \"$95,400\" ],\r\n");
      out.write("\t\t\t\t[ \"Suki Burks\", \"Developer\", \"London\", \"6832\", \"2009/10/22\",\r\n");
      out.write("\t\t\t\t\t\t\"$114,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Prescott Bartlett\", \"Technical Author\", \"London\", \"3606\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/05/07\", \"$145,000\" ],\r\n");
      out.write("\t\t\t\t[ \"Gavin Cortez\", \"Team Leader\", \"San Francisco\", \"2860\",\r\n");
      out.write("\t\t\t\t\t\t\"2008/10/26\", \"$235,500\" ],\r\n");
      out.write("\t\t\t\t[ \"Martena Mccray\", \"Post-Sales support\", \"Edinburgh\", \"8240\",\r\n");
      out.write("\t\t\t\t\t\t\"2011/03/09\", \"$324,050\" ],\r\n");
      out.write("\t\t\t\t[ \"Unity Butler\", \"Marketing Designer\", \"San Francisco\",\r\n");
      out.write("\t\t\t\t\t\t\"5384\", \"2009/12/09\", \"$85,675\" ] ];\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#example').DataTable({\r\n");
      out.write("\t\t\t\tdata : dataSet,\r\n");
      out.write("\t\t\t\tcolumns : [ {\r\n");
      out.write("\t\t\t\t\ttitle : \"Name\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttitle : \"Position\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttitle : \"Office\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttitle : \"Extn.\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttitle : \"Start date\"\r\n");
      out.write("\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\ttitle : \"Salary\"\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Employee Details</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("<table id=\"example\" class=\"display\" width=\"100%\"></table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
